[{assign var="sModuleUrl" value=$oViewConf->getModuleUrl('bestitamazonpay4oxid')}]
[{oxstyle include="`$sModuleUrl`out/src/css/bestitamazonpay4oxid.css"}]
[{if $oViewConf->wasJSCodeInjected('scripts') === false}]
    [{if $oViewConf->getAmazonLoginIsActive()}]
        [{assign var="sAmazonWidgetUrl" value=$oViewConf->getAmazonProperty('sAmazonLoginWidgetUrl')}]
    [{else}]
        [{assign var="sAmazonWidgetUrl" value=$oViewConf->getAmazonProperty('sAmazonWidgetUrl')}]
    [{/if}]
    [{assign var="sAmazonSellerId" value=$oViewConf->getAmazonConfigValue('sAmazonSellerId')}]

    [{oxscript include="`$sAmazonWidgetUrl`?sellerId=`$sAmazonSellerId`" priority=1}]
    [{oxscript include="`$sModuleUrl`out/src/js/bestitamazonpay4oxid.js" priority=11}]
    [{$oViewConf->setJSCodeInjected('scripts')}]
[{/if}]